name: CI
on:
  pull_request:
  push:

env:
  # define Java options for both official sbt and sbt-extras
  JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
  JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 17
            distribution: zulu
            jobtype: 1
          - os: ubuntu-latest
            java: 17
            distribution: zulu
            jobtype: 2
          - os: ubuntu-latest
            java: 25
            distribution: temurin
            jobtype: 1
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
        cache: sbt
    - uses: sbt/setup-sbt@v1
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: |
        sbt -v "+scalafmtCheckAll ; scalafmtSbtCheck ; +scoptJS/test ; +scoptJVM/test"
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v +scoptNative/test
    - name: Cleanup before cache
      shell: bash
      run: rm -rf "$HOME/.ivy2/local"
